import "../../globals.css";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";

import type { Metadata } from "next";
import { Jersey_15, Kanit } from "next/font/google";
import { MantineProvider } from "@mantine/core";

const jersey = Jersey_15({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-jersey",
});
const kanit = Kanit({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-kanit",
});

export const metadata: Metadata = {
  title: "Michał Haj - Resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jersey.variable} ${kanit.variable}`}>
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
